Finalize new version of check_dns_record

diff --git a/functions/check_dns_record b/functions/check_dns_record
--- a/functions/check_dns_record
+++ b/functions/check_dns_record
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-dna-check_dns_record_address() {
+dna-check_dns_record() {
 
 	### This function verifies DNS "address" records [A/AAAA]. For other types of checks see other functions below.
 
@@ -12,18 +12,20 @@ dna-check_dns_record_address() {
 
 		Must be a DNS name [e.g. ae.os.vu]
 
+	Type:
+
+		Must be either:
+
+			a
+			aaaa
+			srv
+
 	Reference:
 
 		Must be either:
 
-			1] A string with a space-separated list of IPs
+			1] A string with a comma-separated list of values [no spaces] [e.g.: "1.1.1.1,2.2.2.2,4.4.4.4,8.8.8.8"]
 			2] An absolute path to a file with a newline-separated list of IPs
-
-	Version:
-
-		Must be either:
-			1] 4 [for IPv4]
-			2] 6 [for IPv6]
 
 	# '
 
@@ -31,21 +33,19 @@ dna-check_dns_record_address() {
 
 	if [ $# -eq 0 ]
     then
-        echo "${r-}${b-}No argument supplied for function | ${FUNCNAME[0]} |.${x-}"
-        echo
+        dna-echo -m "${r-}No argument supplied for function | ${FUNCNAME[0]} |."
         dna-exit
     fi
 
-    while getopts ":n:r:v:" arguments; do
+    while getopts ":n:t:r:" arguments; do
         case $arguments in
             n)	name="$OPTARG"
 	            ;;
+			t)	type="$OPTARG"
+	            ;;
 			r)	reference="$OPTARG"
 	            ;;
-			v)	version="$OPTARG"
-	            ;;
-            \?)	echo "${r-}${b-}Invalid option | -$OPTARG | for function | ${FUNCNAME[0]} |.${x-}"
-	            echo
+            \?)	dna-echo -m "${r-}Invalid option | -$OPTARG | for function | ${FUNCNAME[0]} |."
 	            dna-exit
 	            ;;
         esac
@@ -54,29 +54,26 @@ dna-check_dns_record_address() {
 
     if [ -z "${name-}" ]
     then
-        echo "${r-}${b-}Name [option | -n |] must be supplied for function | ${FUNCNAME[0]} |.${x-}"
-        echo
+        dna-echo -m "${r-}Name [option | -n |] must be supplied for function | ${FUNCNAME[0]} |."
+        dna-exit
+    fi
+
+	if [ -z "${type-}" ]
+    then
+        dna-echo -m "${r-}Type [option | -t |] must be supplied for function | ${FUNCNAME[0]} |."
         dna-exit
     fi
 
 	if [ -z "${reference-}" ]
     then
-        echo "${r-}${b-}Reference [option | -r |] must be supplied for function | ${FUNCNAME[0]} |.${x-}"
-        echo
-        dna-exit
-    fi
-
-	if [ -z "${version-}" ]
-    then
-        echo "${r-}${b-}Version [option | -v |] must be supplied for function | ${FUNCNAME[0]} |.${x-}"
-        echo
+        dna-echo -m "${r-}Reference [option | -r |] must be supplied for function | ${FUNCNAME[0]} |."
         dna-exit
     fi
 
 	############################################################################
 
 	dns_checks_dir="/tmp/dns_checks"
-	name_file_path="${dns_checks_dir}/${name}-v${version}"
+	name_file_path="${dns_checks_dir}/${type}-${name}"
 
 	mkdir -p "${dns_checks_dir}"
 
@@ -99,27 +96,52 @@ dna-check_dns_record_address() {
 	else
 		### Write specified array to a text file
 		reference_file_path="${dns_checks_dir}/reference"
-		echo "${reference}" | tr " " "\n" > "${reference_file_path}"
+		echo "${reference}" | tr "," "\n" > "${reference_file_path}"
 	fi
 
 	readarray -t reference_array < "${reference_file_path}"
 
 	############################################################################
 
+	if [ "${type}" = "a" ]
+	then
+		version=4
+	elif [ "${type}" = "aaaa" ]
+	then
+		version=6
+	fi
+
+	### Convert $type to uppercase for printed messages
+
+	type_name="$(echo ${type} | awk '{print toupper($0)}')"
+
+	############################################################################
+
 	lookup_name(){
 
-		getent ahostsv"${version}" "${name}" | grep STREAM | cut -d' ' -f1 > "${name_file_path}"
+		if [ ! -z "${version-}" ]
+		then
+
+			getent ahostsv"${version}" "${name}" | grep STREAM | cut -d' ' -f1 > "${name_file_path}"
+
+		elif [ "${type}" = "srv" ]
+		then
+
+			host -t srv "${name}" | sed -n -e 's/^.*has SRV record //p' > "${name_file_path}"
+
+		fi
+
 		readarray -t name_array < "${name_file_path}"
 
 	}
 
 	array_contains() {
 	    local array="$1[@]"
-	    local seeking=$2
+	    local seeking="$2"
 	    local in=1
 	    for element in "${!array-null}"
 		do
-	        if [[ $element == $seeking ]]
+	        if [[ "$element" == "$seeking" ]]
 			then
 	            in=0
 	            break
@@ -140,13 +162,13 @@ dna-check_dns_record_address() {
 
 			lookup_name
 
-			result="$(array_contains name_array ${reference_item} && echo y || echo n)"
+			result=$(array_contains name_array "${reference_item}" && echo y || echo n)
 
 	        if [ "${result}" = "y" ]
 	        then
 
-	            echo "${g-}${b-}The IPv${version} address record | ${x-}${reference_item_name}${g-}${b-} | for DNS name | ${x-}${name}${g-}${b-} | is registered correctly.${x-}"
-				echo
+	            dna-echo -m "${g-}The | ${n-}${type_name}${g-} | record | ${n-}${reference_item_name}${g-} | for DNS name | ${n-}${name}${g-} | is registered correctly."
+
 				outcome="ok"
 				accept="y"
 
@@ -157,26 +179,26 @@ dna-check_dns_record_address() {
 				if [ "${incorrect_iteration}" = "1" ]
 				then
 
-		            echo "${r-}${b-}The IPv${version} address record | ${x-}${reference_item_name}${r-}${b-} | for DNS name | ${x-}${name}${r-}${b-} | is NOT registered.${x-}"
-					echo
+					dna-echo -m "${r-}The | ${n-}${type_name}${r-} | record | ${n-}${reference_item_name}${r-} | for DNS name | ${n-}${name}${r-} | is NOT registered."
 
 					if [ "${autoset_dns-null}" = "y" ]
 					then
-						echo "${b-}Automatically setting this record on your DNS provider.${x-}"
-						echo
+
+						dna-echo -m "Automatically setting this record on your DNS provider."
 						outcome="autofix"
 						dna-set_dns_record [...]
+
 					else
-						echo "${g-}${b-}You must now set this record on the authoritative DNS provider for this zone.${x-}"
-						echo
+
+						dna-echo -m "You must now set this record on the authoritative DNS provider for this zone."
+
 						if [ "${dns_provider_setup-null}" = "y" ]
 						then
 							ask_for_boolean_question="Would you like to automatically set this record on [one of] your previously specified DNS provider[s]?"
 				            dna-ask_for_boolean_def_yes
 				            if [ "$ask_for_boolean_output" = "y" ]
 				            then
-								echo "${b-}Ok, automatically setting this DNS record.${x-}"
-								echo
+								dna-echo -m "Ok, automatically setting this DNS record."
 								outcome="autofix"
 								dna-set_dns_record [...]
 							else
@@ -189,18 +211,17 @@ dna-check_dns_record_address() {
 							echo
 							outcome="manualfix"
 						fi
+
 					fi
 
 				elif [ "${incorrect_iteration}" -le "4" ]
 				then
 
-					echo "${r-}${b-}The IPv${version} address record | ${x-}${reference_item_name}${r-}${b-} | for DNS name | ${x-}${name}${r-}${b-} | still appears NOT to be registered.${x-}"
-					echo
+					dna-echo -m "${r-}The | ${n-}${type_name}${r-} | record | ${n-}${reference_item_name}${r-} | for DNS name | ${n-}${name}${r-} | still appears NOT to be registered."
 
 					if [ "${outcome}" = "manualfix" ]
 					then
-						echo "${b-}As we wait to ensure DNS propagation, ensure you've correctly set the record on your DNS provider.${x-}"
-						echo
+						dna-echo -m "As we wait to ensure DNS propagation, ensure you've correctly set the record on your DNS provider."
 					fi
 
 					wait="$[${incorrect_iteration}**2]"
@@ -223,12 +244,9 @@ dna-check_dns_record_address() {
 
 				else
 
-					echo "${r-}${b-}The IPv${version} address record | ${x-}${reference_item_name}${r-}${b-} | for DNS name | ${x-}${name}${r-}${b-} | still appears NOT to be registered after several lookups.${x-}"
-					echo
-					echo "${b-}This could be due to longer than normal TTLs on your DNS records [therefore making propagation longer] or an incorrect setting on your DNS provider.${x-}"
-					echo
-					echo "${b-}Also ensure you're applying the correct setting to the authoritative DNS provider for this zone.${x-}"
-					echo
+					dna-echo -m "${r-}The | ${n-}${type_name}${r-} | record | ${n-}${reference_item_name}${r-} | for DNS name | ${n-}${name}${r-} | still appears NOT to be registered after several lookups."
+					dna-echo -m "his could be due to longer than normal TTLs on your DNS records [therefore making propagation longer] or an incorrect setting on your DNS provider."
+					dna-echo -m "Also ensure you're applying the correct setting to the authoritative DNS provider for this zone."
 
 					until [ "${valid-null}" = "y" ]
 					do
@@ -244,19 +262,16 @@ dna-check_dns_record_address() {
 								accept=n
 								;;
 							s)	echo -e "\\n"
-								echo "${b-}Ok, skipping DNS check for this record...${x-}"
-								echo
+								dna-echo -m "Ok, skipping DNS check for this record..."
 								valid=y
 								accept=y
 								;;
 							e)	echo -e "\\n"
-								echo "${b-}Exiting...${x-}"
-								echo
+								dna-echo -m "Exiting..."
 								exit
 								;;
 							*)	echo -e "\\n"
-								echo "${b-}Invalid option. Try again...${x-}"
-								echo
+								dna-echo -m "${r-}Invalid option. Try again..."
 								valid=n
 								accept=n
 								;;
@@ -314,13 +329,13 @@ dna-check_dns_record_address() {
 
 			calculate_extra_diff
 
-			result="$(array_contains diff_array ${diff_item} && echo y || echo n)"
+			result=$(array_contains diff_array "${diff_item}" && echo y || echo n)
 
 			if [ "${result}" = "n" ]
 	        then
 
-				echo "${g-}${b-}The IPv${version} address record | ${x-}${diff_item_name}${g-}${b-} | for DNS name | ${x-}${name}${g-}${b-} | has been correctly removed.${x-}"
-				echo
+				dna-echo -m "${g-}The | ${n-}${type_name}${g-} | record | ${n-}${diff_item_name}${g-} | for DNS name | ${n-}${name}${g-} | has been correctly removed."
+
 				outcome="ok"
 				accept="y"
 
@@ -331,26 +346,26 @@ dna-check_dns_record_address() {
 				if [ "${incorrect_iteration}" = "1" ]
 				then
 
-					echo "${r-}${b-}The IPv${version} address record | ${x-}${diff_item_name}${r-}${b-} | for DNS name | ${x-}${name}${r-}${b-} | is registered but should NOT be.${x-}"
-					echo
+					dna-echo -m "${r-}The | ${n-}${type_name}${r-} | record | ${n-}${diff_item_name}${r-} | for DNS name | ${n-}${name}${r-} | is registered but should NOT be."
 
 					if [ "${autoset_dns-null}" = "y" ]
 					then
-						echo "${b-}Automatically removing this record on your DNS provider.${x-}"
-						echo
+
+						dna-echo -m "Automatically removing this record on your DNS provider."
 						outcome="autofix"
 						dna-set_dns_record [...]
+
 					else
-						echo "${b-}You must now remove this record on the authoritative DNS provider for this zone.${x-}"
-						echo
+
+						dna-echo -m "You must now remove this record on the authoritative DNS provider for this zone."
+
 						if [ "${dns_provider_setup-null}" = "y" ]
 						then
 							ask_for_boolean_question="Would you like to automatically remove this record on [one of] your previously specified DNS provider[s]?"
 				            dna-ask_for_boolean_def_yes
 				            if [ "$ask_for_boolean_output" = "y" ]
 				            then
-								echo "${b-}Ok, automatically removing this DNS record.${x-}"
-								echo
+								dna-echo -m "Ok, automatically removing this DNS record."
 								outcome="autofix"
 								dna-set_dns_record [...]
 							else
@@ -363,18 +378,17 @@ dna-check_dns_record_address() {
 							echo
 							outcome="manualfix"
 						fi
+
 					fi
 
 				elif [ "${incorrect_iteration}" -le "4" ]
 				then
 
-					echo "${r-}${b-}The IPv${version} address record | ${x-}${diff_item_name}${r-}${b-} | for DNS name | ${x-}${name}${r-}${b-} | still appears to be registered even though it should NOT be.${x-}"
-					echo
+					dna-echo -m "${r-}The | ${n-}${type_name}${r-} | record | ${n-}${diff_item_name}${r-} | for DNS name | ${n-}${name}${r-} | still appears to be registered even though it should NOT be."
 
 					if [ "${outcome}" = "manualfix" ]
 					then
-						echo "${b-}As we wait to ensure DNS propagation, ensure you've correctly removed the record on your DNS provider.${x-}"
-						echo
+						dna-echo -m "As we wait to ensure DNS propagation, ensure you've correctly removed the record on your DNS provider."
 					fi
 
 					wait="$[${incorrect_iteration}**3]"
@@ -397,12 +411,9 @@ dna-check_dns_record_address() {
 
 				else
 
-					echo "${r-}${b-}The IPv${version} address record | ${x-}${diff_item_name}${r-}${b-} | for DNS name | ${x-}${name}${r-}${b-} | still appears to be registered after several lookups even though it should NOT be.${x-}"
-					echo
-					echo "${b-}This could be due to longer than normal TTLs on your DNS records [therefore making propagation longer] or an incorrect setting on your DNS provider.${x-}"
-					echo
-					echo "${b-}Also ensure you're removing the record from the authoritative DNS provider for this zone.${x-}"
-					echo
+					dna-echo -m "${r-}The | ${n-}${type_name}${r-} | record | ${n-}${diff_item_name}${r-} | for DNS name | ${n-}${name}${r-} | still appears to be registered after several lookups even though it should NOT be."
+					dna-echo -m "This could be due to longer than normal TTLs on your DNS records [therefore making propagation longer] or an incorrect setting on your DNS provider."
+					dna-echo -m "Also ensure you're removing the record from the authoritative DNS provider for this zone."
 
 					until [ "${valid-null}" = "y" ]
 					do
@@ -418,19 +429,16 @@ dna-check_dns_record_address() {
 								accept=n
 								;;
 							s)	echo -e "\\n"
-								echo "${b-}Ok, skipping DNS check for this record...${x-}"
-								echo
+								dna-echo -m "Ok, skipping DNS check for this record..."
 								valid=y
 								accept=y
 								;;
 							e)	echo -e "\\n"
-								echo "${b-}Exiting...${x-}"
-								echo
+								dna-echo -m "Exiting..."
 								exit
 								;;
 							*)	echo -e "\\n"
-								echo "${b-}Invalid option. Try again...${x-}"
-								echo
+								dna-echo -m "Invalid option. Try again..."
 								valid=n
 								accept=n
 								;;
@@ -450,9 +458,10 @@ dna-check_dns_record_address() {
 
 	done
 
-	echo "${g-}${b-}All DNS checks for DNS name | ${x-}${name}${g-}${b-} | completed successfully.${x-}"
-	echo
+	dna-echo -m "${g-}All | ${n-}${type_name}${g-} | DNS checks for name | ${n-}${name}${g-} | completed successfully."
 
 	rm -rf "${dns_checks_dir}"
+
+	unset name type version reference
 
 }
