Further code review and improvements

diff --git a/functions/install_dependencies b/functions/install_dependencies
--- a/functions/install_dependencies
+++ b/functions/install_dependencies
@@ -2,18 +2,20 @@
 
 dna-install_dependencies() {
 
+    ############################################################################
+
     if [ $# -eq 0 ]
     then
-        echo "${r-}${b-}No argument supplied for function | ${FUNCNAME[0]} |.${x-}"
-        echo
+        dna-echo -e "No argument supplied for function | ${r-}${FUNCNAME[0]}${n-} |."
         dna-exit
     fi
 
-    while getopts ":ep:" arguments; do
-        case $arguments in
+    while getopts ":ep:" arguments
+    do
+        case "${arguments}" in
             e)	allow_errors="y"
                 ;;
-            p)	packages="$OPTARG"
+            p)	packages="${OPTARG}"
                 ;;
             \?)	dna-echo -e "Invalid option | ${n-}-$OPTARG${r-} | for function | ${n-}${FUNCNAME[0]}${r-} |."
                 dna-exit
@@ -24,39 +26,37 @@ dna-install_dependencies() {
 
     if [ -z "${packages-}" ]
     then
-        echo "${r-}${b-}Packages [option | -p |] must be supplied for function | ${FUNCNAME[0]} |.${x-}"
-        echo
+        dna-echo -e "Option | ${n-}packages [-p]${r-} | must be supplied for function | ${n-}${FUNCNAME[0]}${r-} |."
         dna-exit
     fi
 
-    echo "${b-}Now installing dependencies...${x-}"
-    echo
+    operation_message="installing dependencies"
+
+    dna-echo_operation -h
 
     dna-check_dpkg_availability
 
     dna-apt_update
 
-    if ! apt-get -y install $packages
+    if ! apt-get -y install "${packages}"
     then
+        echo
         if [ "${allow_errors-null}" = "y" ]
         then
-            echo
-            echo "${r-}${b-}An error occured performing APT operations.${x-}"
-            echo
-            echo "${b-}If this is an upgrade [rather than a first install] it is possible that by continuing the installation this and any other errors collected along the way will be fixed automatically.${x-}"
-            echo
-            boolean_question="Would you like to continue the installation anyway?"
-            dna-ask_for_boolean_def_no
-            if [ "$boolean_output" = "n" ]
+            dna-echo -e "An error occured performing APT operations."
+            dna-echo -m "If this is an upgrade [rather than a first install] it is possible that by continuing the installation this and any other errors collected along the way will be fixed automatically."
+
+            dna-ask_for_boolean -d "n" -q "Would you like to continue the installation anyway?"
+
+            if [ "$boolean_output" = "y" ]
             then
-                dna-exit
+                dna-echo -m "Ok, continuing installation anyway..."
             else
-                echo "${b-}Ok, continuing installation anyway...${x-}"
+                dna-echo -m "Ok, aborting..."
+                dna-exit
             fi
         else
-            echo
-            echo "${r-}${b-}An error occured performing APT operations.${x-}"
-            echo
+            dna-echo -e "An error occured performing APT operations."
             dna-exit
         fi
     fi
@@ -65,8 +65,7 @@ dna-install_dependencies() {
 
     set -e
 
-    echo "${g-}${b-}Finished installing dependencies.${x-}"
-    echo
+    dna-echo_operation -t
 
     unset allow_errors
     unset packages
