Fixed indentation

diff --git a/apt_full_upgrade b/apt_full_upgrade
--- a/apt_full_upgrade
+++ b/apt_full_upgrade
@@ -2,37 +2,37 @@
 
 os-apt_full_upgrade() {
 
-        while getopts ":e" arguments; do
-		case $arguments in
-			e)	allow_errors="y"
-				;;
-			\?)	echo "${r}${b}Invalid option | -$OPTARG | for function | ${FUNCNAME[0]} |.${x}"
-				echo
-				os-exit_function
-				;;
-		esac
-	done
+    while getopts ":e" arguments; do
+        case $arguments in
+            e)	allow_errors="y"
+            ;;
+            \?)	echo "${r}${b}Invalid option | -$OPTARG | for function | ${FUNCNAME[0]} |.${x}"
+            echo
+            os-exit_function
+            ;;
+        esac
+    done
 
-        echo "${b}Now performing APT upgrade, dist-upgrade, and autoremove...${x}"
-        echo
+    echo "${b}Now performing APT upgrade, dist-upgrade, and autoremove...${x}"
+    echo
 
-        if [ "${allow_errors-null}" = "y" ]
-	then
-		set +e
-	fi
+    if [ "${allow_errors-null}" = "y" ]
+    then
+        set +e
+    fi
 
-	apt-get -y update
-	apt-get -y upgrade
-	apt-get -y dist-upgrade
-	apt-get -y autoremove
+    apt-get -y update
+    apt-get -y upgrade
+    apt-get -y dist-upgrade
+    apt-get -y autoremove
 
-        echo
+    echo
 
-	set -e
+    set -e
 
-        OPTIND=1
+    OPTIND=1
 
-        echo "${b}Finished performing APT upgrade, dist-upgrade, and autoremove.${x}"
-        echo
+    echo "${b}Finished performing APT upgrade, dist-upgrade, and autoremove.${x}"
+    echo
 
 }
diff --git a/install_dependencies b/install_dependencies
--- a/install_dependencies
+++ b/install_dependencies
@@ -2,44 +2,44 @@
 
 os-install_dependencies() {
 
-        if [ $# -eq 0 ]
-        then
-                echo "${r}${b}No argument supplied for function | ${FUNCNAME[0]} |.${x}"
-                echo
-                os-exit_function
-        fi
-
-        while getopts ":ep:" arguments; do
-		case $arguments in
-			e)	allow_errors="y"
-				;;
-                        p)	packages="$OPTARG"
-                                ;;
-			\?)	echo "${r}${b}Invalid option | -$OPTARG | for function | ${FUNCNAME[0]} |.${x}"
-				echo
-				os-exit_function
-				;;
-		esac
-	done
-
-        echo "${b}Now installing dependencies...${x}"
+    if [ $# -eq 0 ]
+    then
+        echo "${r}${b}No argument supplied for function | ${FUNCNAME[0]} |.${x}"
         echo
+        os-exit_function
+    fi
 
-        if [ "${allow_errors-null}" = "y" ]
-	then
-		set +e
-	fi
+    while getopts ":ep:" arguments; do
+        case $arguments in
+            e)	allow_errors="y"
+            ;;
+            p)	packages="$OPTARG"
+            ;;
+            \?)	echo "${r}${b}Invalid option | -$OPTARG | for function | ${FUNCNAME[0]} |.${x}"
+            echo
+            os-exit_function
+            ;;
+        esac
+    done
 
-        apt-get update
-        apt-get -y install "$packages"
+    echo "${b}Now installing dependencies...${x}"
+    echo
 
-        echo
+    if [ "${allow_errors-null}" = "y" ]
+    then
+        set +e
+    fi
 
-        set -e
+    apt-get update
+    apt-get -y install "$packages"
 
-        echo "${b}Finished installing dependencies.${x}"
-        echo
+    echo
 
-        OPTIND=1
+    set -e
+
+    echo "${b}Finished installing dependencies.${x}"
+    echo
+
+    OPTIND=1
 
 }
diff --git a/run_install b/run_install
--- a/run_install
+++ b/run_install
@@ -2,73 +2,73 @@
 
 os-run_install() {
 
-        ### Set bash environment error management
+    ### Set bash environment error management
 
-        set -e
-        set -u
+    set -e
+    set -u
 
+    echo
+
+    now="$(date +"%Y-%m-%d_%H-%M-%S")"
+
+    ### Define latest version
+    export latest_vers="$(grep 'refs/tags/' $source_dir/.git/packed-refs | tail -1 | awk '{print $2}' | sed "s|refs/tags/v||g")"
+
+    base_dir=/root/$author_name
+    install_dir=$base_dir/$short_name
+    conf_dir=$install_dir/conf
+
+    ### Launch the installer
+
+    if [ -f $conf_dir/beta ]
+    then
+        echo "- * - !!! - * - !!! - * - !!! - * - !!! - * - !!! - * - !!! - * - !!! - * - !!! -"
+        echo
+        echo "Installing bleeding-edge version of $short_name up to latest git commit."
+        echo
+        echo "[delete the | $conf_dir/beta | file to cancel your opt-in to bleeding-edge versions]"
+        echo
+        echo "- * - !!! - * - !!! - * - !!! - * - !!! - * - !!! - * - !!! - * - !!! - * - !!! -"
+        ( cd $source_dir && bash ./install --return-check )
+    else
+        echo "Installing $short_name v$latest_vers"
+        echo
+        ( cd $source_dir && git checkout tags/v$latest_vers && bash ./install --return-check )
+    fi
+
+    ### Read the installer exit code and exit the script
+
+    if [ -f $source_dir/install_complete ]
+    then
+
+        echo "${g-}${b-}Installation complete.${x-}"
         echo
 
-        now="$(date +"%Y-%m-%d_%H-%M-%S")"
+        ### Set installation complete checkfile with installed version
 
-        ### Define latest version
-        export latest_vers="$(grep 'refs/tags/' $source_dir/.git/packed-refs | tail -1 | awk '{print $2}' | sed "s|refs/tags/v||g")"
+        cp $conf_dir/version/version_initiated $conf_dir/version/version_installed
 
-        base_dir=/root/$author_name
-        install_dir=$base_dir/$short_name
-        conf_dir=$install_dir/conf
+        ### Remove installer directory
 
-        ### Launch the installer
+        echo "${b-}Now removing installer directory...${x-}"
+        echo
+        echo "${b-}Run | ${g-}git clone https://github.com/$author_name/$proj_name${x-}${b-} | once again to download the latest installer."
+        echo
 
-        if [ -f $conf_dir/beta ]
-        then
-                echo "- * - !!! - * - !!! - * - !!! - * - !!! - * - !!! - * - !!! - * - !!! - * - !!! -"
-        	echo
-                echo "Installing bleeding-edge version of $short_name up to latest git commit."
-                echo
-                echo "[delete the | $conf_dir/beta | file to cancel your opt-in to bleeding-edge versions]"
-                echo
-                echo "- * - !!! - * - !!! - * - !!! - * - !!! - * - !!! - * - !!! - * - !!! - * - !!! -"
-                ( cd $source_dir && bash ./install --return-check )
-        else
-                echo "Installing $short_name v$latest_vers"
-                echo
-        	( cd $source_dir && git checkout tags/v$latest_vers && bash ./install --return-check )
-        fi
+        rm -r $source_dir
 
-        ### Read the installer exit code and exit the script
+        echo "${b-}Exiting installer.${x-}"
+        echo
 
-        if [ -f $source_dir/install_complete ]
-        then
+    else
 
-                echo "${g-}${b-}Installation complete.${x-}"
-                echo
+        echo "${r-}${b-}The installation has encountered an error.${x-}"
+        echo
+        echo "${b-}Please inspect the any error messages above and try the installation again or open an issue on GitHub. Thank you.${x-}"
+        echo
 
-                ### Set installation complete checkfile with installed version
+        os-exit_function
 
-                cp $conf_dir/version/version_initiated $conf_dir/version/version_installed
-
-                ### Remove installer directory
-
-                echo "${b-}Now removing installer directory...${x-}"
-                echo
-                echo "${b-}Run | ${g-}git clone https://github.com/$author_name/$proj_name${x-}${b-} | once again to download the latest installer."
-                echo
-
-                rm -r $source_dir
-
-                echo "${b-}Exiting installer.${x-}"
-                echo
-
-        else
-
-                echo "${r-}${b-}The installation has encountered an error.${x-}"
-                echo
-                echo "${b-}Please inspect the any error messages above and try the installation again or open an issue on GitHub. Thank you.${x-}"
-                echo
-
-                os-exit_function
-
-        fi
+    fi
 
 }
